spring:
  application:
    name: CUSTOMER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/customers
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Use the generic version compatible with Hibernate 6/7
        dialect: org.hibernate.dialect.MySQLDialect


server:
  port: 2002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka

